#!/bin/bash
# Post-deployment configuration script
# Retrieves stack outputs and configures application

set -e

# Color codes
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Default values
ENVIRONMENT="dev"
STACK_NAME=""
OUTPUT_FILE=".env"

# Parse command line arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --environment|-e)
            ENVIRONMENT="$2"
            shift 2
            ;;
        --stack-name|-s)
            STACK_NAME="$2"
            shift 2
            ;;
        --output|-o)
            OUTPUT_FILE="$2"
            shift 2
            ;;
        --help|-h)
            echo "Usage: $0 [OPTIONS]"
            echo ""
            echo "Options:"
            echo "  --environment, -e ENV    Environment name (dev, staging, prod)"
            echo "  --stack-name, -s NAME    CloudFormation stack name"
            echo "  --output, -o FILE        Output file (default: .env)"
            echo "  --help, -h               Show this help message"
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
done

# Set stack name if not specified
if [ -z "$STACK_NAME" ]; then
    # Load prefix from config
    CONFIG_FILE="config/${ENVIRONMENT}.yaml"
    if [ -f "$CONFIG_FILE" ]; then
        PREFIX=$(python3 -c "import yaml; print(yaml.safe_load(open('$CONFIG_FILE'))['project']['prefix'])" 2>/dev/null || echo "sc-agent-${ENVIRONMENT}")
    else
        PREFIX="sc-agent-${ENVIRONMENT}"
    fi
    STACK_NAME="${PREFIX}-stack"
fi

echo "📋 Post-Deployment Configuration"
echo "Environment: $ENVIRONMENT"
echo "Stack Name: $STACK_NAME"
echo ""


# Get AWS region
AWS_REGION=${AWS_REGION:-$(aws configure get region)}
AWS_REGION=${AWS_REGION:-us-east-1}

echo "Retrieving stack outputs from CloudFormation..."

# Function to get stack output
get_output() {
    local output_key=$1
    aws cloudformation describe-stacks \
        --stack-name "$STACK_NAME" \
        --region "$AWS_REGION" \
        --query "Stacks[0].Outputs[?OutputKey=='$output_key'].OutputValue" \
        --output text 2>/dev/null || echo ""
}

# Retrieve all outputs
ATHENA_BUCKET=$(get_output "AthenaResultsBucketName")
USER_POOL_ID=$(get_output "UserPoolId")
USER_POOL_CLIENT_ID=$(get_output "UserPoolClientId")
API_ENDPOINT=$(get_output "APIEndpoint")
CONVERSATION_TABLE=$(get_output "ConversationTableName")
SQL_EXECUTOR_FUNCTION=$(get_output "SqlExecutorFunctionName")
INVENTORY_OPTIMIZER_FUNCTION=$(get_output "InventoryOptimizerFunctionName")
LOGISTICS_AGENT_FUNCTION=$(get_output "LogisticsAgentFunctionName")
SUPPLIER_ANALYZER_FUNCTION=$(get_output "SupplierAnalyzerFunctionName")

# Check if we got the outputs
if [ -z "$API_ENDPOINT" ]; then
    echo -e "${YELLOW}⚠${NC} Warning: Could not retrieve all stack outputs"
    echo "Stack may still be deploying or stack name may be incorrect"
    echo "Stack name used: $STACK_NAME"
    exit 1
fi

echo -e "${GREEN}✓${NC} Stack outputs retrieved successfully"
echo ""

# Append to .env file (preserve existing config)
echo "Updating $OUTPUT_FILE with deployment outputs..."

# Create backup
if [ -f "$OUTPUT_FILE" ]; then
    cp "$OUTPUT_FILE" "${OUTPUT_FILE}.backup"
fi

# Append deployment outputs
cat >> "$OUTPUT_FILE" << EOF

# Deployment Outputs (Generated by post-deploy.sh)
# Environment: $ENVIRONMENT
# Deployed: $(date)

# AWS Resources
AWS_REGION=$AWS_REGION
ATHENA_OUTPUT_LOCATION=s3://$ATHENA_BUCKET/
CONVERSATION_TABLE_NAME=$CONVERSATION_TABLE

# Cognito
USER_POOL_ID=$USER_POOL_ID
USER_POOL_CLIENT_ID=$USER_POOL_CLIENT_ID

# API Gateway
API_ENDPOINT=$API_ENDPOINT

# Lambda Functions
SQL_EXECUTOR_FUNCTION=$SQL_EXECUTOR_FUNCTION
INVENTORY_OPTIMIZER_FUNCTION=$INVENTORY_OPTIMIZER_FUNCTION
LOGISTICS_AGENT_FUNCTION=$LOGISTICS_AGENT_FUNCTION
SUPPLIER_ANALYZER_FUNCTION=$SUPPLIER_ANALYZER_FUNCTION

EOF

echo -e "${GREEN}✓${NC} Configuration updated: $OUTPUT_FILE"
echo ""


# Store outputs in Parameter Store for easy retrieval
echo "Storing outputs in Parameter Store..."

PARAM_PREFIX="/${PREFIX}"

# Function to put parameter
put_parameter() {
    local param_name=$1
    local param_value=$2
    
    if [ -n "$param_value" ]; then
        aws ssm put-parameter \
            --name "${PARAM_PREFIX}/${param_name}" \
            --value "$param_value" \
            --type String \
            --overwrite \
            --region "$AWS_REGION" \
            --tags "Key=Environment,Value=$ENVIRONMENT" "Key=ManagedBy,Value=deployment-script" \
            &> /dev/null
        
        if [ $? -eq 0 ]; then
            echo "  ✓ Stored: ${PARAM_PREFIX}/${param_name}"
        fi
    fi
}

put_parameter "api-endpoint" "$API_ENDPOINT"
put_parameter "user-pool-id" "$USER_POOL_ID"
put_parameter "user-pool-client-id" "$USER_POOL_CLIENT_ID"
put_parameter "athena-bucket" "$ATHENA_BUCKET"
put_parameter "conversation-table" "$CONVERSATION_TABLE"

echo -e "${GREEN}✓${NC} Outputs stored in Parameter Store"
echo ""

# Display summary
echo "========================================="
echo "Deployment Summary"
echo "========================================="
echo "Environment:     $ENVIRONMENT"
echo "Region:          $AWS_REGION"
echo "Stack:           $STACK_NAME"
echo ""
echo "API Endpoint:    $API_ENDPOINT"
echo "User Pool:       $USER_POOL_ID"
echo "Athena Bucket:   $ATHENA_BUCKET"
echo "Conversation DB: $CONVERSATION_TABLE"
echo ""
echo "Configuration saved to: $OUTPUT_FILE"
echo "Parameters stored at:   $PARAM_PREFIX/*"
echo "========================================="
